#!/bin/bash

LD_PRELOAD=/lib/aarch64-linux-gnu/libgcc_s.so.1 vncserver -localhost no -depth 24 -name remote-desktop -AcceptSetDesktopSize=0 $GEO :$PORT
echo "Servidor VNC iniciado. A senha e a mesma configurada para $USER"
