#!/bin/bash

read -sp 'Digite uma nova senha para o servidor VNC: ' PASSWORD
/usr/bin/vncpasswd -f <<<"$PASSWORD"$'\n'"$PASSWORD" > $HOME/.vnc/passwd
echo ""
echo "Senha de VNC configurada com sucesso..."
