#!/bin/bash

USER=$(whoami)
echo "Encerrando VNC Server"
echo -n "Qual porta do sistema a conexao estava usando e vc deseja fechar (Exemplo: 3): "
read pt
echo " "
echo "Encerrando a porta $pt"
vncserver -kill :$pt
rm -rf /tmp/.X$pt-lock
rm -rf /tmp/.X11-unix/X$pt
